SERIAL_DRIVER = vendor
#SPACE SAVING
AUDIO_ENABLE = no
MUSIC_ENABLE = no
# LTO must be disabled for RP2040 builds
LTO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no

COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes